name: GoodSPAWN
main: ifteam\GoodSPAWN\GoodSPAWN
version: 0.4-alpha
author: ifteam
api:
- 1.4.1
- 1.12.0
- 1.13.0
- 2.0.0

permissions:
 goodspawn.spawn:
  default: true
 goodspawn.setspawn:
  default: op
 goodspawn.spawnclear:
  default: op